<img src="photos/amirkabir-uni-logo.jpg" style="margin-left:auto; margin-right:auto"/>
<img src="photos/ce-logo.png" style="margin-left:auto; margin-right:auto"/>

<div style="font-size: 30px"> <center> Linear Algebra </center></div>
<center> fall 2023 </center>
<center> Instructor: </center>
<center> Dr.Ehsan Nazerfard </center> <br>
<center> TAs: </center>
<center> Sara Rouhani, 
Amir Hossein Poulad, 
Mohammad Heydari Rad, 
Asal Delkhosh, 
Mohammad Hossein Aref, 
Amir Mohammad Jafari, 
Samin Mahdi Pour, 
Mohammad Eshrat Abadi </center>

#### <div style="text-align: center; color: #888888; font-size: 30px">پروژه اول درس جبر خطی کاربردی</div>
#### <div style="text-align: center; color: #888888">محاسبه جریان گذرنده از مدار های الکتریکی</div>

<div style="text-align: right">
در این پروژه قصد داریم به وسیله جبر خطی و قوانینی که در درس مدار های الکتریکی یاد گرفته ایم، جریان گذرنده از سیم های مدار زیر را محاسبه کنیم
<br/><br/>
تصویر زیر را مشاهده میکنید
<br/>
این تصویر نشان دهنده بخشی از یک مدار است، جهت جریان هر سیم با یک پیکان روی آن مشخص شده و برای بعضی از آن ها میزان جریان نیز به میلی آمپر نوشته شده است
<br/>
</div>

<img src="photos/flow.png" style="margin-left:auto; margin-right:auto"/>

<div style="text-align: right">
هدف ما این است که جریان های مجهول این بخش از مدار را پیدا کنیم
</div>

<div style="text-align: right">
از درس مدار های الکتریکی میدانیم که مجموع جریان های ورودی به هر گره مدار صفر است
<br/>
گره های مدار همان نقاط زیر هستند:
<br/>
A, B, C, D
</div>

<div style="text-align: right">
برای گره های نام برده شده این قانون را اعمال میکنیم
</div>

<div>
A:
<br/>
x1 + x2 = 800
<br/>
B:
<br/>
x2 - x3 + x4 = 300
<br/>
C:
<br/>
x4 + x5 = 500
<br/>
D:
<br/>
x1 + x5 = 600
</div>

<div style="text-align: right">
ماتریس افزوده معادلات به دست آمده را مینویسیم
</div>

1, 1, 0, 0, 0, 800
<br/>
0, 1, -1, 1, 0, 300
<br/>
0, 0, 0, 1, 1, 500
<br/>
1, 0, 0, 0, 1, 600

<div style="text-align: right">
برای حل این مسئله، میخواهیم تابعی بنویسیم که یک ماتریس افزوده میگیرد و به فرم ماتریس نردبانی کاهش یافته در می آورد
</div>

<div style="text-align: right">
در درس جبر خطی دیده ایم که برای تبدیل یک ماتریس به فرم نردبانی کاهش یافته آن باید مراحل زیر را انجام دهیم
<br/>
قدم اول
<br/>
با جا به جایی سطر ها، کاری میکنیم که چپ ترین مدخل غیر صفر هر سطری، در زیر یا سمت راست چپ ترین مدخل غیر صفر هر سطر بالایی اش قرار بگیرد
<br/>
قدم دوم
<br/>
چپ ترین مدخل غیر صفر بالا ترین سطری که برایش شاخص در نظر نگرفته ایم را به عنوان شاخص در نظر میگیریم
<br/>
تمام سطر هایی که زیر این شاخص مقداری غیر صفر دارند را منهای ضریبی از سطر اول میکنیم که برابر حاصل تقسیم شاخص بر چپ ترین مدخل غیر صفر آن سطر است
<br/>
و اگر فرم بالا مثلثی به هم خورد به قدم اول میرویم
<br/>
قدم سوم
<br/>
تمامی سطر های دارای شاخص را بر مقدار شاخصشان تقسیم میکنیم
<br/>
قدم چهارم
<br/>
هر سطری که بالا سر شاخصی مدخلی غیر صفر دارد را منهای حاصل ضرب آن مدخل در سطر آن شاخص میکنیم تا مدخل های بالای هر شاخص صفر بشود
</div>

<div style="text-align: right; color: red">
توجه: شما باید کدی بنویسید که هر ماتریس افزوده ای را به فرم نردبانی کاهش یافته ببرد، نه صرفا ماتریس افزوده این مدار الکتریکی، و باید بتوان ماتریس افزوده را به آن ورودی داد و خروجی را مشاهده کرد
</div>

<div style="text-align: right; color: red">
توجه: اصراری بر استفاده از کد های  زیر نیست، میتوانید آنطور که میخواهید آن ها را تغییر دهید، توابع جدید اضافه کنید یا حذفشان کنید و کد های خود را بنویسید، صرفا باید در نهایت تابعی داشته باشید که بتوان به آن ماتریس افزوده داد و آن به فرم ماتریس نردبانی کاهش یافته در بیاورد و نمایش دهد
</div>

<div style="text-align: right; color: red">
توجه: لطفا کد ها را تا حد امکان کامنت گذاری کنید و توضیح دهید
</div>

<div style="text-align: right; color: green">
در صورت وجود هرگونه ابهام، از طریق ایمیل تدریسیاری سوال خود را بپرسید</br>
linearalgebra.fall1401@gmail.com</div>

<div style="text-align: right; color: green">
پاسخ خود را در قالب فایلی با نام زیر آپلود کنید</br>
P1_Name_StudentNumber.ipynb</div>

In [29]:
! pip install numpy

In [30]:
import numpy as np
tol = 1e-10

<div style="text-align: right">
برای این کار در ابتدا باید توابعی را پیاده سازی کنیم که عملیات کاهش سطری را انجام میدهند
</div>

<div style="text-align: right">
جا به جایی دو سطر
<br/>
این تابع یک ماتریس و اندیس دو سطر را میگیرد و آن دو سطر را در آن ماتریس جا به جا میکند
</div>

In [43]:
def interchange(matrix, first_row_index, second_row_index):
#     interchange two given rows
    matrix[[first_row_index, second_row_index]] = matrix[[second_row_index, first_row_index]]

<div style="text-align: right">
تقسیم سطر بر یک عدد
<br/>
این تابع یک ماتریس و اندیس سطر و یک عدد میگیرد و تمام درایه های آن سطر را به آن عدد تقسیم میکند
</div>

In [44]:
def divide_row_by_scalar(matrix, row_index, scalar):
#     divide entries of a row by given scalar
    return np.divide(matrix[row_index], scalar)

<div style="text-align: right">
ضرب سطر در یک عدد
<br/>
این تابع یک ماتریس و اندیس سطر و یک عدد میگیرد و تمام درایه های آن سطر را در آن عدد ضرب میکند
</div>

In [45]:
def multiply_row_by_scalar(matrix, row_index, scalar):
#     multiply entries of a row to given scalar
    return np.multiply(matrix[row_index], scalar)

<div style="text-align: right">
تفریق یک سطر با ضریبی از سطر دیگر
<br/>
این تابع یک ماتریس و اندیس دو سطر و یک عدد را میگیرد و حاصل ضرب دومی در عدد را از سطر اول کم میکند و به جای سطر اول میگذارد
</div>

In [46]:
def replace(matrix, first_row_index, second_row_index, scalar):
    matrix[first_row_index] = matrix[first_row_index] - multiply_row_by_scalar(matrix, second_row_index, scalar)

<div style="text-align: right">
قدم اول و پیدا کردن pivot positions
</div>

In [47]:
def upper_triangle_form_and_pivots(matrix):
    row_index = 0
    num_columns = matrix.shape[1]
    num_rows = matrix.shape[0]
    #     store pivot positions in pivot array
    pivots = []
    #     iterate on columns and find first element of a column that is not zero then
    #     interchange its row with row_index that is the row index that we are searching pivot for it
    for i in range(num_columns):
        #         all rows are ok
        if row_index == matrix.shape[0]:
            break

        column_i = matrix[:, i]
        for j in range(row_index, num_rows):
            if column_i[j] != 0:
                interchange(matrix, row_index, j)
                pivots.append([row_index, i])
                #                 now this row is ok so we add 1 to it
                row_index += 1
                break
    return pivots

<div style="text-align: right">
قدم دوم
</div>

In [48]:
# make entries below of a pivot zero
def subtract_scaled_pivot_row_from_rows_below(matrix, pivots):
    #     iterate on pivots and check all entries below it, if they were nonzero make it zero with replace method
    for pivot_position in pivots:
        for i in range(pivot_position[0] + 1, matrix.shape[0]):
            if matrix[i][pivot_position[1]] != 0:
                replace(matrix, i, pivot_position[0],
                        matrix[i][pivot_position[1]] / matrix[pivot_position[0]][pivot_position[1]])

    #     to make sure again convert it to triangle form
    return upper_triangle_form_and_pivots(matrix)

<div style="text-align: right">
قدم سوم
</div>

In [49]:
# divide rows by their pivot entries to make all pivot values 1
def divide_rows_by_their_pivot_entries(matrix, pivots):
    for pivot in pivots:
        matrix[pivot[0]] = divide_row_by_scalar(matrix, pivot[0], matrix[pivot[0]][pivot[1]])

<div style="text-align: right">
قدم چهارم
</div>

In [50]:
# make entries above of each pivot zero
def subtract_scaled_pivot_row_from_rows_above(matrix, pivots):
    for pivot in pivots:
        for i in range(pivot[0] - 1, -1, -1):
            if i < 0:
                break
            if matrix[i][pivot[1]] != 0:
                replace(matrix, i, pivot[0], matrix[i][pivot[1]] / matrix[pivot[0]][pivot[1]])

<div style="text-align: right">
تابع نهایی: این تابع ماتریس افزوده را میگیرد و به فرم نردبانی کاهش یافته در می آورد و خروجی را برمیگرداند
</div>

In [51]:
def reduced_echelon_form(augmented_matrix):
    #     convert entries to longdouble
    augmented_matrix = augmented_matrix.astype(np.longdouble)
    #     make it reduced echelon form
    pivots = upper_triangle_form_and_pivots(augmented_matrix)
    pivots = subtract_scaled_pivot_row_from_rows_below(augmented_matrix, pivots)
    divide_rows_by_their_pivot_entries(augmented_matrix, pivots)
    subtract_scaled_pivot_row_from_rows_above(augmented_matrix, pivots)
    #     round it in a way that if it is smaller than tol make it zero
    augmented_matrix.real[abs(augmented_matrix.real) < tol] = 0.0
    return augmented_matrix

<div style="text-align: right">
تست تابع با ماتریس افزوده توصیف شده
</div>

In [53]:
augmented_matrix = np.array([
    [1, 1, 0, 0, 0, 800],
    [0, 1, -1, 1, 0, 300],
    [0, 0, 0, 1, 1, 500],
    [1, 0, 0, 0, 1, 600]
])
test = np.array([
    [0, 1, 5, -4],
    [1, 4, 3, -2],
    [2, 7, 1, -2]
])
test1 = np.array([
    [2, 0, -6, 8],
    [0, 1, 2, 3],
    [3, 6, -2, -4]
])
test2 = np.array([
    [1, 4, 7, 0],
    [2, 5, 8, 0],
    [3, 6, 9, 0]
])
test3 = np.array([
    [40.543677, 76.621599, 14.610784, 23.334928, 83.347119],
    [88.206170, 35.211003, 82.973952, 67.427483, 84.639442],
    [10.116170, 90.252630, 14.369531, 82.252769, 30.430778],
    [60.631609, 56.553448, 17.243585, 61.737453, 40.757826],
    [24.522159, 38.365846, 40.851396, 18.420055, 20.534812]
])
test4 = np.array([
    [98.08, 79.36, 21.06, 40.49, 39.10],
    [79.25, 89.30, 11.01, 43.31, 49.63],
    [85.76, 95.37, 26.30, 73.92, 32.43],
    [46.76, 38.00, 32.13, 46.03, 78.18],
    [95.80, 60.94, 69.28, 84.71, 48.57]
])
test5 = np.array([
    [44.311, 27.828, 91.499, 24.511, 18.736],
    [33.178, 96.371, 88.894, 39.656, 55.242],
    [97.732, 68.836, 26.070, 22.280, 95.357],
    [41.091, 66.550, 72.356, 18.420, 78.056],
    [52.656, 69.025, 17.642, 21.768, 65.583]
])
test6 = np.array([
    [79, 58, 31, 46, 61],
    [49, 52, 76, 33, 19]
])
test7 = np.array([
    [50, 77],
    [60, 77],
    [32, 13],
    [45, 68],
    [72, 71]
])
test8 = np.array([
    [0, 1],
    [1, 1]
])
print(reduced_echelon_form(augmented_matrix))

[[  1.   0.   0.   0.   1. 600.]
 [  0.   1.   0.   0.  -1. 200.]
 [  0.   0.   1.   0.   0. 400.]
 [  0.   0.   0.   1.   1. 500.]]
